export const GET_FEATURED_JOB_SUCCESS = "GET_FEATURED_JOB_SUCCESS";
export const GET_FEATURED_JOB_FAILED = "GET_FEATURED_JOB_FAILED";
export const GET_FEATURED_JOB_LOADING = "GET_FEATURED_JOB_LOADING";
